import type { Metadata } from 'next'
import styles from './styles.module.scss';
import Navigation from '@/components/Navigation';
import { Providers } from '@/components/Provider';
import Top from '@/components/Top';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode,
}) {
  const isLogedIn = false
  return (
    <html lang="en">
      
      <body className={styles.layoutWrapper}>
        <Providers>
          <div className={styles.top}>
            <Top/>
          </div>
          <div className={styles.main}>
            {/* {isLogedIn &&
              <Navigation/>
            } */}
            {children}
          </div>
        </Providers>
        
      </body>
    </html>
  )
}
